version: '3'

services:
    timepunch:
        container_name: timepunch
        build: ./
        restart: unless-stopped
        ports:
          - 3030:3000
        volumes:
            - ./data:/usr/src/app/data